#!/usr/bin/env python
import random

print """Zgadnij i podaj liczbe o ktorej mysle: """
PCs_number = random.randint(1,100)
users_number = ""

while users_number != PCs_number:
    users_number = input()
    if (users_number > PCs_number):
        print "Moja liczba jest mniejsza"
    elif (users_number < PCs_number):
        print "Moja licza jest wieksza"

print "Gratulacje! Zgadles!" 
